### ISSUE TITLE
Got an Error while i execute pushnotification.php

### ISSUE THREAD

**Issue by DhiralKaniya** [carlosCharz/FCMTest#1]
{
  "multicast_id": 9024402724089112854,
  "success": 0,
  "failure": 1,
  "canonical_ids": 0,
  "results": [
    {
      "error": "InvalidRegistration"
    }
  ]
}

**Comment by carlosCharz** [comment]
I answered that in your comment in youtube. This is not an issue. This is a valid error code from google when there is a problem with the token you are trying to reach.
